//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispositivo
    {
        public Dispositivo()
        {
            this.Dispositivo_Estatus = new HashSet<Dispositivo_Estatus>();
            this.Historial = new HashSet<Historial>();
        }
    
        public int DispositivoID { get; set; }
        public short ModeloID { get; set; }
        public string NumeroSerie { get; set; }
        public string Espesificaciones { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
        public System.DateTime FechaHora { get; set; }
    
        public virtual Asignacion Asignacion { get; set; }
        public virtual ICollection<Dispositivo_Estatus> Dispositivo_Estatus { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual ICollection<Historial> Historial { get; set; }
    }
}
