//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estatus
    {
        public Estatus()
        {
            this.Dispositivo_Estatus = new HashSet<Dispositivo_Estatus>();
            this.Modelo = new HashSet<Modelo>();
        }
    
        public byte EstatusID { get; set; }
        public string Clave { get; set; }
        public string Descripcion { get; set; }
        public bool Estatus1 { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
    
        public virtual ICollection<Dispositivo_Estatus> Dispositivo_Estatus { get; set; }
        public virtual ICollection<Modelo> Modelo { get; set; }
    }
}
