//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public long HistorialID { get; set; }
        public int DispositivoID { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string UsuarioAlta { get; set; }
        public string UsuarioResponsable { get; set; }
        public string UsuarioTestigo { get; set; }
        public Nullable<decimal> ValorPagare { get; set; }
        public string ObservacionAlta { get; set; }
        public string UsuarioBaja { get; set; }
        public string FechaBaja { get; set; }
        public string ObservacionBaja { get; set; }
        public System.DateTime FechaHora { get; set; }
    
        public virtual Dispositivo Dispositivo { get; set; }
    }
}
