//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenTI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventarioTIEntities : DbContext
    {
        public InventarioTIEntities()
            : base("name=InventarioTIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Asignacion> Asignacion { get; set; }
        public DbSet<Dispositivo> Dispositivo { get; set; }
        public DbSet<Dispositivo_Estatus> Dispositivo_Estatus { get; set; }
        public DbSet<Estatus> Estatus { get; set; }
        public DbSet<Historial> Historial { get; set; }
        public DbSet<Marca> Marca { get; set; }
        public DbSet<Modelo> Modelo { get; set; }
        public DbSet<TipoDispositivo> TipoDispositivo { get; set; }
    }
}
