//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        public Modelo()
        {
            this.Dispositivo = new HashSet<Dispositivo>();
        }
    
        public short ModeloID { get; set; }
        public short MarcaID { get; set; }
        public byte TipoDispostivoID { get; set; }
        public byte EstatusID { get; set; }
        public string Nombre { get; set; }
        public string Espesificaciones { get; set; }
        public System.DateTime FechaHora { get; set; }
    
        public virtual ICollection<Dispositivo> Dispositivo { get; set; }
        public virtual Estatus Estatus { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual TipoDispositivo TipoDispositivo { get; set; }
    }
}
