//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDispositivo
    {
        public TipoDispositivo()
        {
            this.Modelo = new HashSet<Modelo>();
        }
    
        public byte TipoDispositivoID { get; set; }
        public string Clave { get; set; }
        public string Descripcion { get; set; }
        public bool Estatus { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
    
        public virtual ICollection<Modelo> Modelo { get; set; }
    }
}
